apiVersion: v1
kind: Service
metadata:
  name: abc12
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "abc12"
    port: 8080
  selector:
    app: abc12
